### ISSUE TITLE
x8xx (Network Management) messages are treated as invalid

### ISSUE THREAD

**Issue by timgabets** [zemuldo/iso_8583#2]
```
let data = { 
0: '0100' ,
2: '4761739001010119'
};
let isopack = new iso8583(data);
isopack.validateMessage(); 
> true
```
```
let data = { 
0: '0800',
70: '001'
};
let isopack = new iso8583(data);
isopack.validateMessage(); 
> false
```
x8xx messages are the part of [ISO8583](https://en.wikipedia.org/wiki/ISO_8583#Message_class) as well, and must pass validateMessage() check.

**Comment by zemuldo** [comment]
Hi Tim. Sorry for my  late response.
I will review the fixes and test tomorrow and also see the new version
uploaded.
Thanks.

**Comment by zemuldo** [comment]
Hi Tim
The test for 0800 valid message goes through.
test('getMti() should return proper MTI for 1820', t => {
  let data = {
     0: '0800',
     70: '001'
  };
  let isopack = new Main(data);
  t.is(isopack.validateMessage(), true);
  t.is(isopack.getMti(), '0800');
});
test('getMti() should return proper MTI for 1820', t => {
    let data = {
        0: '1899',
        70: '001'
    };
    let isopack = new Main(data);
    t.is(isopack.validateMessage(), false);
});
All passed

**Comment by zemuldo** [comment]
Hey Tim, I hope you have validated before closing this issue.

**Comment by timgabets** [comment]
Hi, I've seen the covered test case, that's enough for now ;)
