### ISSUE TITLE
Transaction Status Mapping - tools.js

### ISSUE THREAD

**Issue by JCRodger** [zemuldo/iso_8583#26]
getTransStatus, maps to the account types const. great library by the way, thanks.

**Comment by zemuldo** [comment]
Hi @JCRodger, Thanks for the compliment. Please elaborate the issue above.

**Comment by zemuldo** [comment]
@JCRodger Ideally getTransStatus should return what is on field 39 with the descriptive name. I this what you mean?

**Comment by zemuldo** [comment]
The issue should be resolved in version 2.5.4. Please check out and thanks for submitting this issue.

**Comment by JCRodger** [comment]
perfect thanks
