### ISSUE TITLE
Bitmap 32

### ISSUE THREAD

**Issue by msaphira** [zemuldo/iso_8583#36]
Hello, how can i use .getISOJson() to convert iso with 32 bitmap?

**Comment by zemuldo** [comment]
Can I see a sample of the iso message you want to convert?

**Comment by zemuldo** [comment]
How are you passing the buffer to getIsoJSON? That method takes a buffer within which the bitmaps must be encoded in hexadecimal while in memory and will take 16 bytes. If you parse the buffer with bitmap encoded in another encoding, 16 bytes will have only the first bitmap. The two bitmaps each 8 bytes will take up 16 bytes. 
Solution: parse the buffer as you get from the source. If you need to convert a string like the one above, this library doesn't support.
However if that's how your interface has to receive data, we can help u decode.

**Comment by msaphira** [comment]
i'm using another library (socketQueue) to pass the buffer and it works when i use JReactive-8583 library (based in java). 
Now i'm trying to do it  in node js.
Can you give me example how to parse the buffer after i get it from the source?
Thank you :)

**Comment by zemuldo** [comment]
I have checked socketQueue - https://github.com/juks/SocketQueue, Here is what I have to say.
When using data from another source, the data must be encoded such that 
2 bytes containe tcp length header indicator, 4 bytes contain the mti and next 16 bytes contain the bitmaps. Its also possible to have only 8 byte mti.

Here is an example from socketqueue example without leng indicator and only primary bitmap
```
msg = new Buffer('303830302220010000800000393930303030303832333135313731363030303030313833313030303030303031', 'hex');
```

Now parsing this using our iso package, you have to set lenHeader and secondary bitmap to false.

```
console.log(myIsoPack.getIsoJSON(msg, {lenHeader: false, }))
```

This gives 

```
{ '0': '0800',
  '3': '990000',
  '7': '0823151716',
  '11': '000001',
  '24': '831',
  '41': '00000001' }

```

**Comment by zemuldo** [comment]
You have to check how the data you receive is encoded before the mti. That way i can help.

**Comment by msaphira** [comment]
So this library cannot have secondary bitmap? which means that i cannot use data fields from 65-128?

If this library can have a secondary bitmap, would you please give me an example of buffer message with secondary bitmap?

i already tried the example you gave but i got an error message 'failed to unpack at get mti' .

thank you for your help :)

**Comment by zemuldo** [comment]
It supports both bitmaps. Versions below 2.5.7 do not support primary bitmap without secondary bitmap.
Here is a buffer with both bitmaps
```
<Buffer 00 26 31 32 30 30 c0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 31 36 34 37 36 31 37 33 39 30 30 31 30 31 30 31 31 39>
```
And here is a buffer with only primary 
```
<Buffer 30 38 30 30 38 32 32 30 30 30 30 30 30 30 30 30 30 30 30 30 30 34 30 30 30 30 30 30 30 30 30 30 30 30 30 30 31 31 32 35 31 36 31 33 33 36 30 30 30 32 ... >
```

**Comment by zemuldo** [comment]
To make things work, you have to ensure the buffer has a 2 byte length indicator before the mti. If your message starts with the mti then you have to disable the length indicator. check docs for that.

**Comment by msaphira** [comment]
i'm still a bit confuse about this, 

This is my buffer with secondary bitmap
<Buffer 00 37 30 38 30 30 38 32 32 30 30 30 30 30 30 30 30 30 30 30 30 30 30 34 30 30 30 30 30 30 30 30 30 30 30 30 30 30 31 32 31 32 30 31 31 38 34 33 30 30 ... >

it's already shown the two bytes of length indicator --> 00 37, and four bytes of mti --> 30 38 30 30

but how can i convert my 32 bytes bitmap to 16 bytes bitmap which contain primary and secondary bitmap?

**Comment by msaphira** [comment]
i already found a way to convert my incoming buffer. Thank you for your help! :)

**Comment by zemuldo** [comment]
That is very nice to hear. Very welcome. You can post how you converted to
help someone else who may have the same problem. :-)

**Comment by zemuldo** [comment]
I will give you an example here

**Comment by zemuldo** [comment]
Are you still having this issue?

**Comment by msaphira** [comment]
I already solve the issue, thank you :)

**Comment by zemuldo** [comment]
Awesome! You can always post the solution here for someone else who may face a similar issue.
