### ISSUE TITLE
Bitmap Length

### ISSUE THREAD

**Issue by spyndutz** [zemuldo/iso_8583#81]
Hello there, I have an issue here.
I'm trying to unpack a message which consisted of something like this:
4-byte MTI encoded in utf8 + 16-byte Bitmap encoded in hex + Message Field Data
Which fairly refer to [this](https://en.wikipedia.org/wiki/ISO_8583#Bitmaps) Wikipedia
"The bitmap may be represented as 8 bytes of binary data or as 16 hexadecimal characters (0–9, A–F) in the ASCII or EBCDIC character sets."

Thus, I got an ISO8583 string like this: 
`
0200 + F23A400108E1800E + [Message Field Data]
`
I have used the config for { lenHeader: false }.
However, when I tried to unpack the messages, I don't get any error, but the unpacked messages aren't the expected result.
Here's the result I get:
```
{ '0': '0200',
  '2': 'E1800E00',
....
}
```
The 'E1800E' part that should be included in Bitmaps is parsed to the second bit of the messages.
I noticed that it might have something to do in unpack_0_127.js snippet which states
```
// Does data contain a secondary bitmap?
    const secondaryBitmap = this.hasSecondaryBitmap(
      incoming.slice(4, 8),
      config
    );
    if (secondaryBitmap === false) bitmapEnd = 12;
    else bitmapEnd = 20;
```
I wonder is there any config that I miss regarding the expected result?

**Comment by spyndutz** [comment]
The expected active bit should be:
11110010 00111010 01000000 00000001 00001000 11100001 10000000 00001110
Therefore, the given bitmap defines the following fields present in the message:
1, 2, 3, 4, 7, 11, 12, 13, 15, 18, 32, 37, 41, 42, 43, 48, 49, 61, 62, 63

**Comment by zemuldo** [comment]
F23A400108E1800E is your primary bitmap? 
If yes, its binary form is `1111001000111010010000000000000100001000111000011000000000001110` and the first bit there is 1 indicating secondary bitmap is present. 

I have also noticed that the override was not working. So setting {secondaryBitmap: false} in message decoder was not working. So you have two options.

I have made modifications in the beta release [here](https://www.npmjs.com/package/iso_8583/v/2.6.5-beta). If this works for you I can create a PR.
Set the bitmap encoding and presence of secondary bitmap as below or use custom format for field 1 with `an` as the encoding

```javascript
const isopack = new Main();
  const isoString = '0200c000000000000000194761739001010119';
  const config = { lenHeader: false, bitmapEncoding: 'utf8', secondaryBitmap: false, };
  const message = isopack.getIsoJSON(new Buffer.alloc(isoString.length, isoString), config);

  t.is(message[0], '0200');
  t.is(message[2], '4761739001010119');

  const isopack1 = new Main(message);
  isopack1.setBitMapEncoding('utf8');
  isopack1.setSecondaryBitmap(false);
  const messageBuf1 = isopack1.getBufferMessage();
  const message1 = isopack.getIsoJSON(messageBuf1, {...config, lenHeader: true});

  t.is(message1[0], '0200');
  t.is(message[2], '4761739001010119');
```

**Comment by spyndutz** [comment]
I don't know whether I explain my problem clearly there.
However, by adding these config:

**Comment by zemuldo** [comment]
Nice! You can update the docs and PR 😄
